global:
  scrape_interval: 15s  # Set default scrape interval to 15 seconds

scrape_configs:
  - job_name: 'ec2-node'
    static_configs:
      - targets: ['X.X.X.X:9100']  #Replace with Instance Public Ip Address
